import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import { Twitter, LinkedinSquare ,Github, Instagram} from 'styled-icons/boxicons-logos'
import { Blog } from 'styled-icons/icomoon'
import { getAllPosts } from '@/lib/posts'
import {Post} from '@/components/index'
import {device} from '@/utils/devices'
const TopContainer = styled.div`
display: flex;
height: 70vh;
flex-direction: column;
align-items: center;
justify-content: center;
margin-right: auto;
margin-left: auto;
text-align: center;

`
const Title = styled.h1`
font-size:3rem;
color:#000;

`
const TitleSpan = styled.span`
color:#0070f3

`

const Motto = styled.p`
font-weight: 300;
font-size:1.5rem;

`
const SocialLinks = styled.ul`
list-style: none;
margin: 0;
padding: 0;
display: flex;
gap: 2rem;
font-size: 1.25rem;
line-height: 1.75rem;
margin-top: 1rem;

`
const BlueBlog = styled(Blog)`
color:#0070f3
`

const BlueTwitter = styled(Twitter)`
color:#0070f3
`
const BlueLinkedIn = styled(LinkedinSquare)`
color:#0070f3
`
const BlueGithub = styled(Github)`
color:#0070f3
`

const BlueInstagram = styled(Instagram)`
color:#0070f3
`
const BodyContainer = styled.div`
width: 100%;
margin:auto;
display:grid;
gap:4rem;
margin:3rem auto;
/* background: #EAEEF4; */

@media ${device.tablet}{
grid-template-columns: repeat(2, 1fr);
};
@media ${device.laptop}{
grid-template-columns: repeat(3, 1fr);
}
`
const PostHeading = styled.h1`
color:#0070f3;
font-size:3rem;
font-weight:bold;
border-bottom:4px solid #330;




`
export default function Home({posts}) {


  return (
    <div className={styles.container}>
   
      <Head>
        <title>Mcwachira&#8216;s Blog and Portfolio site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopContainer>
        <Title>
          Hi I&#8216;m  <TitleSpan>Charles Wachira</TitleSpan>
          <Motto>
            Fullstack Software developer helping startup&#8216; s build software using Javascript.
          </Motto>
        </Title>

        <SocialLinks>
          <li>
            <a href="">
              <BlueBlog size='30' />
            </a>
          </li>
        <li>
       <a href="">
              <BlueTwitter size='30' />
       </a>
        </li>
          <li>
            <a href="">
              <BlueLinkedIn size='30'/>
            </a>
          </li>
          <li>
            <a href="">
              <BlueGithub size='30' />
            </a>
          </li>
          <li>
            <a href="">
              <BlueInstagram size='30' />
            </a>
          </li>
        </SocialLinks>
      </TopContainer>
     

      <PostHeading>
        Latest Posts
      </PostHeading>
      <BodyContainer>
        {posts.map((post, index) => (
          <Post key={index} post={post} />
        ))}

      </BodyContainer>
    </div>
  )
}



//always return an object with getStaticProps
export const getStaticProps = async () => {

  const posts = getAllPosts().slice(0, 6)


  return {
    props: {
       posts
    }
  }
}